Repository demaceo/rantom, pull requests merged in 2020-12, with the labels that each got.

#1 Display movies
  .eslintcache
  src/App.js
  src/Catalogue.css
  src/Catalogue.js
  src/MovieCard.css
  src/MovieCard.js
  src/mockData.js
Labels: enhancement

#12 Display single movie
  .eslintcache
  src/App.js
  src/Components/Catalogue/Catalogue.css
  src/Components/Catalogue/Catalogue.js
  src/Components/Catalogue/Catalogue.test.js
  src/Components/MovieCard/MovieCard.css
  src/Components/MovieCard/MovieCard.js
  src/Components/MovieCard/MovieCard.test.js
  src/Components/NavBar/NavBar.css
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.test.js
  src/Components/SelectedMovie/SelectedMovie.css
  src/Components/SelectedMovie/SelectedMovie.js
  src/Components/SelectedMovie/SelectedMovie.test.js
  src/MovieCard.js
  src/mockMovie.js
Labels: enhancement

#21 Async testing
  src/App.js
  src/App.scss
  src/App.test.js
  src/Components/FeaturedMovies/FeaturedMovies.js
  src/Components/MovieCard/MovieCard.test.js
  src/Components/NavBar/NavBar.test.js
  src/Components/SelectedMovie/SelectedMovie.test.js
Labels: enhancement, refactor, testing

#22 Router refactor
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/Components/Catalogue/Catalogue.js
  src/Components/FeaturedMovies/FeaturedMovies.js
  src/Components/FeaturedMovies/FeaturedMovies.scss
  src/Components/Home/Home.js
  src/Components/Home/Home.scss
  src/Components/Home/Home.test.js
  src/Components/Loader/Loader.js
  src/Components/Loader/Loader.scss
  src/Components/Loader/Loader.test.js
  src/Components/MovieCard/MovieCard.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/SelectedMovie/SelectedMovie.js
  src/index.js
Labels: Error Handling, Router, enhancement, refactor

#23 Add testing files to components
  .eslintcache
  src/App.js
  src/App.test.js
  src/Components/Catalogue/Catalogue.test.js
  src/Components/FeaturedMovies/Featured.test.js
  src/Components/FeaturedMovies/FeaturedMovies.js
  src/Components/Home/Home.js
  src/Components/Home/Home.test.js
  src/Components/Loader/Loader.test.js
  src/Components/SelectedMovie/SelectedMovie.js
  src/Components/SelectedMovie/SelectedMovie.scss
Labels: enhancement, testing

#24 Refactor TDD
  .eslintcache
  src/App.js
  src/App.test.js
  src/Components/Catalogue/Catalogue.test.js
  src/Components/FeaturedMovies/Featured.test.js
  src/Components/FeaturedMovies/FeaturedMovies.js
  src/Components/Home/Home.js
  src/Components/Home/Home.test.js
  src/Components/Loader/Loader.test.js
  src/Components/MovieCard/MovieCard.test.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.test.js
  src/Components/SelectedMovie/SelectedMovie.js
  src/Components/SelectedMovie/SelectedMovie.scss
  src/Components/SelectedMovie/SelectedMovie.test.js
Labels: enhancement, refactor, testing

#25 Testing cc
  src/App.js
  src/App.test.js
  src/Components/Catalogue/Catalogue.js
  src/Components/Catalogue/Catalogue.test.js
  src/Components/Home/Home.js
  src/Components/Home/Home.test.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MovieCard/MovieCard.test.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.test.js
Labels: Error Handling, testing

#26 Choose Your Own Adventure
  .eslintcache
  src/App.js
  src/Components/DropMenu/DropMenu.js
  src/Components/DropMenu/DropMenu.scss
  src/Components/MovieCard/MovieCard.scss
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/SelectedMovie/SelectedMovie.js
  src/Components/SelectedMovie/SelectedMovie.scss
  src/index.css
  src/index.js
Labels: Router, enhancement, testing

#27 Selected movie refactor
  src/App.js
  src/App.scss
  src/App.test.js
  src/Components/Catalogue/Catalogue.js
  src/Components/Catalogue/Catalogue.test.js
  src/Components/DropMenu/DropMenu.js
  src/Components/DropMenu/DropMenu.scss
  src/Components/DropMenu/DropMenu.test.js
  src/Components/FeaturedMovies/Featured.test.js
  src/Components/FeaturedMovies/FeaturedMovies.scss
  src/Components/Loader/Loader.js
  src/Components/Loader/Loader.test.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MovieCard/MovieCard.scss
  src/Components/MovieCard/MovieCard.test.js
  src/Components/NavBar/NavBar.scss
  src/Components/SelectedMovie/SelectedMovie.js
  src/Components/SelectedMovie/SelectedMovie.scss
  src/Components/SelectedMovie/SelectedMovie.test.js
  src/index.css
Labels: Error Handling, bug, enhancement
